### ISSUE TITLE
体验反馈

### ISSUE THREAD

**Issue by LazyCuteLion** [JamesnetGroup/leagueoflegends-wpf#7]
View使用【.cs+style】的方式，无法在设计视图中实时查看效果，在我看来，这会造成极大的不方便……尽管可以热重载。
对于WPF，我认为设计视图真的非常方便、有用、高效。
还有一点小问题，tab切换较为卡顿，是加载了大量图片的原因？

**Comment by jamesnet214** [comment]
@LazyCuteLion Thank you for your feedback. The DesignView is much more convenient than hot reload.

This repository may present learning challenges for those unfamiliar with CustomControl-based project design. However, CustomControl-based design offers many advantages beyond the limitation of not being able to use the designer view.

For example, it enables distributed project design, distributed resource management based on CustomControl, and non-hierarchical design optimized for dependency injection. While it may sacrifice design convenience, it's highly effective from an architectural perspective. Furthermore, by properly utilizing ContentControl and ItemsControl features of the CustomControl approach, you can easily implement complex functionality with sophisticated design patterns. CustomControl is not only one of the most crucial elements of WPF but also a core concept that applies across all XAML-based platforms.

For more detailed information, please refer to these articles:
- https://jamesnset.dev/articles/38
- @vickyqu115's article: https://www.bilibili.com/opus/997272572701704198

Regarding the tab switching lag, there could be several causes:
- PC environment
- Asynchronous processing during menu transitions

Screens are instantiated and registered for dependency injection when menus are called. This dynamic screen creation during menu transitions can cause lag. If you want to address this, try implementing asynchronous processing in the menu selection process.

You can also contribute to our project. Feel free to submit Pull Requests with your good ideas. Note that this repository is designed as a single framework to work across WPF, Uno Platform, WinUI3, and UWP, with cross-platform compatibility being our top priority.

We'll work on adding the guide improvements and Pull Request participation instructions you mentioned.

Thank you.

**Comment by LazyCuteLion** [comment]
使用这样的方式可以支持设计视图（我的疑问点在于，为何要定义资源字典而不是这样）：
<james:WPFView x:Class="Leagueoflegends.Main.UI.Views.MainContent"
               xmlns:james="clr-namespace:Jamesnet.Windows;assembly=Jamesnet.Windows"
               ……>

</james:WPFView>
cs 文件：
public partial class MainContent : WPFView // 使用“partial”
{
    public MainContent()
    {
        DefaultStyleKey = typeof(MainContent);
        this.InitializeComponent();//调用该方法
    }
}

**Comment by jamesnet214** [comment]
Yes, that approach works fine.

However, the main reason for using CustomControl in views like MainContent is to enable more flexible individual implementation of ControlTemplates and independent resource management.

If you prefer using UserControl instead of CustomControl, that's perfectly acceptable. It's entirely a matter of developer preference.
